baseURL = 'https://iisnrl.github.io/CIoT_DataDoc/'
#languageCode = "en-US"
languageCode = "zh"
defaultContentLanguage = "zh"

title = 'CIoT DataDoc'
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/IISNRL/CIoT_DataDoc/tree/main/content/"
  description = "CIoT Open Data Application - Documentation/Learning Project"
  author = "Ling-Jyh Chen"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = false
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"

[taxonomies]
  category = "categories"
  tag = "tags"
  level = "levels"
  author = "author"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Tutorial for CIoT Open Data Applications"
weight = 1
languageName = "English"
landingPageURL = "/CIoT_DataDoc/en"
landingPageName = "<i class='fas fa-home'></i> Home"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/IISNRL/CIoT_DataDoc"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Showcases"
url = "showcase"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

[Languages.zh]
#title = "Hugo 主题的 Learn 文档"
title = "Tutorial for CIoT Open Data Applications"
weight = 3
languageName = "中文"
landingPageURL = "/CIoT_DataDoc/zh"
landingPageName = "<i class='fas fa-home'></i> 首頁"

[[Languages.zh.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/IISNRL/CIoT_DataDoc"
weight = 10

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> 展示區"
url = "/showcase"
weight = 11

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Hugo 文件"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> 致謝"
url = "/credits"
weight = 30

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> 難度等級"
url = "/levels"
weight = 100

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> 標籤"
url = "/tags"
weight = 110

